POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Make 1",
    "model": "Model 1",
    "year": 2008,
    "mileage": 12500,
    "lng": 14.58501591830241,
    "lat": 0,
    "price": 156500
}

### Approve an existing report
PATCH http://localhost:3000/reports/18
Content-Type: application/json

{
    "approved": false
}

### Gest an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Make%201&model=Model%201&lng=14&lat=0&mileage=11000&year=2003